version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    container_name: flask-backend
    ports:
      - "5212:5212"
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
  frontend:
    build:
      context: ./course-planner-ui
      dockerfile: Dockerfile
    env_file:
      - ./course-planner-ui/.env.development
    working_dir: /app
    volumes:
      - ./course-planner-ui:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: yarn dev
