version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: .
    container_name: flask-backend
    env_file:
      - ./.env
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    depends_on:
      - redis
  frontend:
    build:
      context: ./course-planner-ui
      dockerfile: Dockerfile
    env_file:
      - ./course-planner-ui/.env.development
    working_dir: /app
    volumes:
      - ./course-planner-ui:/app
      - /app/node_modules
    ports:
      - "${VITE_PORT:-3000}:${VITE_PORT:-3000}"
    command: yarn dev
